# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fc13d2bb9d5ac1159551ea4023497792cc1555a80df2afa70aafca0ba6df15ae57e5830a55d485abe000dba3f0ded1ab192d3951445d2f0f829f59c05e29e2b

test:
  secret_key_base: f1d910ea753629c0589850880b15dfc681e8523f62baa1ff52fffdc0e91a32f5d5af1e6605634a34282abe23723fe2e2fe1f7f773e513eeb9604a5c4df9c5090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
